user:
    author: Hauke Schulz
    email: hauke.schulz@mpimet.mpg.de
    author_str: &author_str 'Hauke Schulz (hauuke.schulz@mpimet.mpg.de)'
    institute: &institute "Max Planck Institute for Meteorology, Hamburg, Germany"

datasets:
    resampled:
        global_attrs:
            title: "Radar reflectivity on equidistant monotonic increasing time grid"
            author: *author_str
            institute: *institute
            Conventions: "CF-1.6"
        variables:
            Zf:
                attrs:
                    units: "dBZ"
                coordinates:
                    - time
                    - range
            sfc_wind:
                attrs:
                    units: "m/s"
                coordinates:
                    - time

        coordinates:
            time:
                attrs:
                    units: "seconds since 1970-01-01 00:00:00"
                    calendar: "standard"
                    axis: "T"
                    standard_name: "time"
                dimension: ${time_dimension}
            range:
                attrs:
                    units: "m"
                dimension: ${range_dimension}

    labeled:
        global_attrs:
            title: "Cloud entities on equidistant monotonic increasing time grid"
            description: "Cloud labels derived from radar reflectivity smoothed
                            before calculation by stencil to interconnect close-by clouds"
            author: *author_str
            institute: *institute
            Conventions: "CF-1.6"

        coordinates:
            time:
                attrs:
                        #units: "seconds since 1970-01-01 00:00:00"
                        #calendar: "standard"
                    axis: "T"
                    standard_name: "time"
                dimension: ${time_dimension}
            range:
                attrs:
                    units: "m"
                    standard_name: "height"
                dimension: ${range_dimension}
        variables:
            label:
                attrs:
                    stencil: ${stencil_label}
                    reflectiviy_threshold: ${dBZ_threshold}
                    description: "Cloud entities created by applying a stencil to radar
                                        reflectivity field greater than defined threshold"
                    units: ""
                coordinates:
                    - time
                    - range
            Z:
                attrs:
                    units: ""
                coordinates:
                    - time
                    - range
            sfc_wind:
                attrs:
                    units: "m/s"
                coordinates:
                    - time
